version: '3.7'
services:
  db:
    image: mysql:latest
    container_name: local-db
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=password
    volumes:
      - /mysql:/var/lib/mysql
